name: Test
on: [push]
jobs:
  runTests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rails-version: [70]
        ruby-version: [2.7.5, 3.0.4, 3.1.2]
        include:
          - ruby-version: 2.7.5
            rails-version: 60
          - ruby-version: 2.7.5
            rails-version: 61

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails_${{ matrix.rails-version }}.gemfile
      # we do not care about mysql, but it should be fine
      TEST_ADAPTERS: "sqlite3 postgres"

    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: seamless_database_pool_test
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@master
      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: |
          bundle exec appraisal rails_${{ matrix.rails-version }} rspec
